name: Auto Update

on:
  workflow_dispatch:
  schedule:
    # update every 1 hour
    - cron: "0 */12 * * *"

jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Generate new README.md
        run: go run main.go
      - name: Push to repository
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Actions"
              git add .
              git commit -m "auto update"
              git push origin main
              exit 0
          fi
          echo "no changes"
